export const REQUEST_LOGIN = "REQUEST_LOGIN";
export const RESPONSE_LOGIN_SUCCESS = "RESPONSE_LOGIN_SUCCESS";
export const RESPONSE_LOGIN_FAIL = "RESPONSE_LOGIN_FAIL";

export default {
  REQUEST_LOGIN,
  RESPONSE_LOGIN_SUCCESS,
  RESPONSE_LOGIN_FAIL,
};
